
package hangman;

import javax.swing.*;
import java.awt.*;


public class Hangman extends javax.swing.JFrame {
    boolean finished = false;
    /**
     * Creates new form Hangman
     */
    public Hangman() {
        initComponents();
        jLabel1.setVisible(false);
        lblMsg1.setVisible(false);
        
        
       
        
    }
    @Override
    public void paint(Graphics g){
        getContentPane().setBackground(Color.WHITE); 
        g.drawRect(0,0,100,60);
        
        
        //sets background color of form
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        lblMsg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frame 1");
        setAutoRequestFocus(false);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Justin\\Documents\\GitHub\\hangman\\HangmanGUI\\src\\base.png")); // NOI18N

        btnStart.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lblMsg1.setText("The computer has chosen a word");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMsg1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 188, Short.MAX_VALUE)
                        .addComponent(jLabel1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsg1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getAccessibleContext().setAccessibleName("frame1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        String p1name = JOptionPane.showInputDialog(null, "Enter your name: ");
        jLabel1.setVisible(true);
        lblMsg1.setVisible(true);
        
        
        while(!finished){
            String guess = JOptionPane.showInputDialog(null, "Enter your guess");
            getPos(guess);
        }
       
        
      
        
        
    }//GEN-LAST:event_btnStartActionPerformed


    
  public static void getPos(String a){  //gets custom letter to check for
        
        String word = "apple";
        char[] brokenUp = word.toCharArray();
        int firstA = word.indexOf(a);
        int numA = 0;
        char chA = a.charAt(0);
        int posA[] = new int[120];
        for(int i=0; i<brokenUp.length;i++){
            if (brokenUp[i] == chA){
                numA++;
                posA[numA-1] = i;   //idea: make posA an array, each time there is an a, throw i into a new slot in the array.
                            //throw into slot of numA-1
            }       
        }
        if(numA!=0){
            JOptionPane.showMessageDialog(null, "There are " + numA +" "+chA+ "'s in the word", "Alert", 2);
        }
        
        
        if(numA==0){
            JOptionPane.showMessageDialog(null, "There is no "+ chA +" in the word. Try again", "Alert", 1);
        }
        else
        {    
            for(int j=0;j<numA;j++){
                int fakeJ = j + 1;
                int posAJ = posA[j];
                int posAJ1 = posAJ + 1;
                String message;
                if(fakeJ==1){
                    message = "The " + fakeJ + "st occurrence is at position " + posAJ1;
                }
                else if(fakeJ==2){
                    message = "The " + fakeJ + "nd occurrence is at position " + posAJ1;
                }
                else if(fakeJ==3){
                    message = "The " + fakeJ + "rd occurrence is at position " + posAJ1;
                }
                else
                    message = "The " + fakeJ + "th occurrence is at position " + posAJ1;
                System.out.println(message);
            }
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hangman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMsg1;
    // End of variables declaration//GEN-END:variables
}
